from console.controls import ControlsState
import board

# Game loop settings
TARGET_FPS = 30
FRAME_TIME = 1.0 / TARGET_FPS
SCREENSAVER_TIMEOUT_S = 5.0

# LED Display settings
MAIN_MATRIX_WIDTH = 10
MAIN_MATRIX_HEIGHT = 20
SECONDARY_MATRIX_WIDTH = 5
SECONDARY_MATRIX_HEIGHT = 5
LED_STRIP_PIN = board.D10
LED_BRIGHTNESS = 1.0 # 0.0 to 1.0

MAIN_MATRIX_PIX_COUNT = MAIN_MATRIX_WIDTH * MAIN_MATRIX_HEIGHT
SECONDARY_MATRIX_PIX_COUNT = SECONDARY_MATRIX_WIDTH * SECONDARY_MATRIX_HEIGHT
MAIN_MATRIX_OFFSET = 0
SECONDARY_MATRIX_OFFSET = MAIN_MATRIX_PIX_COUNT
LED_STRIP_LEN = MAIN_MATRIX_PIX_COUNT + SECONDARY_MATRIX_PIX_COUNT

# Seven segment display settings
SEVEN_SEGMENT_I2C_ADDRESS = 0x70
SEVEN_SEGMENT_LED_BRIGHTNESS = 15 # 0 to 15 inclusive
SEVEN_SEGMENT_DIGITS = 4

# GPIO pin mappings for physical buttons (BCM)
BUTTON_GPIO_MAPPING = {
    6: ControlsState.BTN_START_HOLD,
    13: ControlsState.BTN_UP_HOLD,
    19: ControlsState.BTN_DOWN_HOLD,
    26: ControlsState.BTN_LEFT_HOLD,
    20: ControlsState.BTN_RIGHT_HOLD,
}

# Audio settings
AUDIO_ASSETS_PATH = "assets/sounds/"
AUDIO_SAMPLE_RATE = 22050
AUDIO_BUFFER_SIZE = 512
